### ISSUE TITLE
POST http://localhost:4201/onebook/book/getMultipleRecommendationBook.form 404 (Not Found)

### ISSUE THREAD

**Issue by terrycafe520** [wangsuse/nvread-app#2]
Hi，My first time to run your app ,but it error like this . How can I fix it  ?

**Comment by terrycafe520** [comment]
It has already done .

**Comment by wangsuse** [comment]
This app needs a backend servicce to support, you can refer to niuread.com to see a demo.

**Comment by terrycafe520** [comment]
when I use the data like this ,I can get the data object.
`         
      data: [{
        type: 'rentals',
        id: 'grand-old-mansion',
        attributes: {
          title: 'Grand Old Mansion'       }
      }]
`
but when I change the data like below ( just add the code and msg ) . I cannot get the data . In the models  I defined the model attr.  Where is the problem's key point ?
`    'code': 200,
      'msg': 'something else'     
      'data': [{
        type: 'rentals',
        id: 'grand-old-mansion',
        attributes: {
          title: 'Grand Old Mansion'       }
      }]
`
